# Generated by Django 6.0.6 on 2026-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='nombre_completo',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
